# Gruvbox palette
set -g @bg        "#282828"
set -g @fg        "#FBF1C7"
set -g @red       "#CC241D"
set -g @green     "#689D6A"
set -g @yellow    "#D79921"
set -g @blue      "#458588"
set -g @purple    "#B16286"
set -g @orange    "#D65D0E"
set -g @grey      "#3C3836"


