# Gruvbox palette
set -g @bg        "#26233a"
set -g @fg        "#e0def4"
set -g @red       "#eb6f92"
set -g @green     "#31748f"
set -g @yellow    "#f6c177"
set -g @blue      "#9ccfd8"
set -g @purple    "#c4a7e7"
set -g @orange    "#ebbcba"
set -g @grey      "#524f67"


