
source-file ~/.config/tmux/gruvbox.conf


set  -g default-terminal "screen"
set  -g base-index      1
setw -g pane-base-index 1

new-session



set -g status-keys vi
set -g mode-keys   vi



# rebind main key: C-a
unbind C-b
set -g prefix C-a
bind -N "Send the prefix key through to the application" \
  C-a send-prefix




set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       500
set  -g history-limit     2000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'


# ============================================= #

	  unbind C-b

	  unbind %
	  unbind '"'
	  unbind c
	  unbind x

	  bind | split-window -h
	  bind - split-window -v
	  bind a new-window
	  bind q killp

	  bind -r C-k resize-pane -U 5
	  bind -r C-j resize-pane -D 5
	  bind -r C-h resize-pane -L 5
	  bind -r C-l resize-pane -R 5

	  bind -r k select-pane -U 
	  bind -r j select-pane -D 
	  bind -r h select-pane -L 
	  bind -r l select-pane -R 

	  unbind Up     
	  unbind Down   
	  unbind Left   
	  unbind Right  

	  unbind C-Up   
	  unbind C-Down 
	  unbind C-Left 
	  unbind C-Right                   
	  
	  set-option -g allow-rename off
	  set -g renumber-windows on

	  set -g pane-border-style "fg=#{@fg}"
	  set -g pane-active-border-style "bg=default fg=#{@green}"

	  set -g status-position top

	  set -g window-status-separator ""
	  set-option -g status-style "bg=default fg=#{@fg}" 
	  set-option -g status-interval 5
	  set-option -g status-left-length 40
	  set-option -g status-left '#[fg=#{@green} bg=default]#[bg=#{@green} fg=#{@bg}] #[bg=#{@green} fg=#{@red}]#[bg=#{@red} fg=#{@bg}]#H#[bg=default fg=#{@red}]#[bg=default fg=#{@fg}]#[bg=default fg=#{@grey}]#[bg=#{@grey} fg=#{@fg}] Session: #S #[bg=default fg=#{@grey}]'
	  set-option -g status-right '#[bg=default fg=#{@orange}]#[bg=#{@orange} fg=#{@bg}] %d/%m/%Y#[bg=#{@orange} fg=#{@yellow}]#[bg=#{@yellow} fg=#{@bg}] %H:%M#[bg=default fg=#{@yellow}]'
	  set -g window-status-current-format "#[bg=default fg=#{@blue}]#[bg=#{@blue},fg=#{@bg}] #W (#I) #[bg=default fg=#{@blue}]"
	  set -g window-status-format "#[bg=default fg=#{@grey}]#[bg=#{@grey},fg=#{@fg}] #W (#I) #[bg=default fg=#{@grey}]"
	  set-option -sa terminal-overrides 'kitty:RGB'

	  bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

		set -g default-terminal "kitty"
		set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # colored underscores
		set -as terminal-overrides ',alacritty:RGB'

	
