include gruvbox.conf
shell_integration fish

background_blur 1
background_opacity 0.900000

confirm_os_window_close 0
copy_on_select clipboard
cursor_beam_thickness 1
cursor_shape beam
cursor_shape_unfocused underline
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 5
enable_audio_bell no
font_family Maple Mono NF
font_size 10
mouse_hide_wait 0
scrollback_lines 2000
window_padding_width 10




